<?php

namespace AppBundle\Repository;

/**
 * BadDomainsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadDomainsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLikeName($name)
    {
        return $this->createQueryBuilder('d')
            ->Where('d.name LIKE :name')
            ->setParameter('name', '%' . $name . '%')
            ->getQuery()
            ->getOneOrNullResult();
    }
}
